# Generated by Django 4.2.2 on 2023-06-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_matchup_ot_loss_team_ot_loss_count_team_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='date',
            field=models.DateField(default='12-31-2050'),
        ),
    ]
